name: Linter

on: push

jobs:
  Super-Linter:
    name: Run Linters
    runs-on: ubuntu-latest
    steps:
      - name: Check code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Run linters
        uses: wearerequired/lint-action@v2
        with:
          eslint: true
          prettier: true
